### ISSUE TITLE
[Feature Request] Expand the list of examples on the Example applications page

### ISSUE THREAD

**Issue by webchick** [temporalio/temporal-learning#311]
(Corresponding internal ticket: EDU-1842)

### Is your feature request related to a problem? Please describe.

Right now, https://learn.temporal.io/examples/ only lists a _single_ example (Background Checker), in a _single_ programming language (Go). A user who's new to Temporal might leave this page with the impression that Temporal is extremely limited in what it can do, and/or in the languages that it supports.

In reality, however, there are TONS of Temporal examples kicking around out there, among them:

* **Reference Applications** such as the newly announced [Order Management System (OMS)](https://github.com/temporalio/reference-app-orders-go)
* **Samples** for each SDK ([samples-go](https://github.com/temporalio/samples-go), [samples-python](https://github.com/temporalio/samples-python), etc.)
* **Demos** which can be less thoroughly documented / polished than the above, but nevertheless are great to highlight a particular use case, design pattern, and/or Temporal feature (there are moves to consolidate these under https://github.com/temporal-sa/)
* **Community-Contributed Examples** a collection of some of these can be found at https://github.com/temporalio/awesome-temporal

But, without doing a bunch of sleuthing and/or without a great deal of random luck, you'd never ever know this as it stands today. 😢 

### Describe the solution you'd like

1. The main thing? **More than one example on that page.** 🤣 
1. Along with this, introducing "categorization/taxonomy" of examples, so that we can start to expand out beyond simply the "end-to-end" applications (which are _far_ less plentiful, and _extremely_ time consuming to create)
1. The simplest thing that can possibly work that accomplishes those two (at least for now).

### Additional context
Community-contributed examples are a bit of a can of worms, so let's leave those out of scope for now. (But... working on it! :))

**Comment by tomwheeler** [comment]
FWIW, I think the OMS should definitely be listed here. 

The SDK samples don't qualify as "Example Applications" in my opinion. They're valuable, for sure, but they're intended to demonstrate the use of a specific API instead of demonstrating how to implement a relatable use case. In some cases (such as the [Expense Reporting sample](https://github.com/temporalio/samples-go/tree/main/expense) for Go intended to  demonstrate asynchronous Activity completion), they get close to what I'd call an example application, but most do not.

The SA demos certainly qualify as "example applications," although I'd say that we should consider inclusion on a case-by-case basis (and only if the developer/maintainer thinks it should be). Some may lack step-by-step instructions that would make it challenging for another person to run. Others may have been created to demonstrate a specific case to a specific group of people and may not be instructive outside that context.
